well_commerce_distribution:
    configuration:
        package:
            orm:
                factory: WellCommerce\Bundle\DistributionBundle\Factory\PackageFactory
                repository: WellCommerce\Bundle\DistributionBundle\Repository\PackageRepository
                mapping: "@WellCommerceDistributionBundle/Resources/config/doctrine/Package.orm.yml"
                entity: WellCommerce\Bundle\DistributionBundle\Entity\Package
